package com.ciaj.boot.modules.my.entity.bo;

import java.util.Date;

public class MyFamily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.name
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.code
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.enabled
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.area_id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.addr
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.description
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.create_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.create_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.update_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.update_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.del_flag
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family.version
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.id
     *
     * @return the value of my_family.id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.id
     *
     * @param id the value for my_family.id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.name
     *
     * @return the value of my_family.name
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.name
     *
     * @param name the value for my_family.name
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.code
     *
     * @return the value of my_family.code
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.code
     *
     * @param code the value for my_family.code
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.enabled
     *
     * @return the value of my_family.enabled
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.enabled
     *
     * @param enabled the value for my_family.enabled
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.area_id
     *
     * @return the value of my_family.area_id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.area_id
     *
     * @param areaId the value for my_family.area_id
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.addr
     *
     * @return the value of my_family.addr
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.addr
     *
     * @param addr the value for my_family.addr
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.description
     *
     * @return the value of my_family.description
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.description
     *
     * @param description the value for my_family.description
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.create_at
     *
     * @return the value of my_family.create_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.create_at
     *
     * @param createAt the value for my_family.create_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.create_time
     *
     * @return the value of my_family.create_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.create_time
     *
     * @param createTime the value for my_family.create_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.update_at
     *
     * @return the value of my_family.update_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.update_at
     *
     * @param updateAt the value for my_family.update_at
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.update_time
     *
     * @return the value of my_family.update_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.update_time
     *
     * @param updateTime the value for my_family.update_time
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.del_flag
     *
     * @return the value of my_family.del_flag
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.del_flag
     *
     * @param delFlag the value for my_family.del_flag
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family.version
     *
     * @return the value of my_family.version
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family.version
     *
     * @param version the value for my_family.version
     *
     * @mbg.generated Wed Jan 14 16:21:00 CST 2026
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}