package com.ciaj.boot.modules.my.entity.bo;

import java.util.Date;

public class MyFamilyMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.family_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String familyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.user_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.type
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.create_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.create_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.update_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.update_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.del_flag
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_member.version
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.id
     *
     * @return the value of my_family_member.id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.id
     *
     * @param id the value for my_family_member.id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.family_id
     *
     * @return the value of my_family_member.family_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.family_id
     *
     * @param familyId the value for my_family_member.family_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setFamilyId(String familyId) {
        this.familyId = familyId == null ? null : familyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.user_id
     *
     * @return the value of my_family_member.user_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.user_id
     *
     * @param userId the value for my_family_member.user_id
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.type
     *
     * @return the value of my_family_member.type
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.type
     *
     * @param type the value for my_family_member.type
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.create_at
     *
     * @return the value of my_family_member.create_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.create_at
     *
     * @param createAt the value for my_family_member.create_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.create_time
     *
     * @return the value of my_family_member.create_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.create_time
     *
     * @param createTime the value for my_family_member.create_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.update_at
     *
     * @return the value of my_family_member.update_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.update_at
     *
     * @param updateAt the value for my_family_member.update_at
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.update_time
     *
     * @return the value of my_family_member.update_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.update_time
     *
     * @param updateTime the value for my_family_member.update_time
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.del_flag
     *
     * @return the value of my_family_member.del_flag
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.del_flag
     *
     * @param delFlag the value for my_family_member.del_flag
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_member.version
     *
     * @return the value of my_family_member.version
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_member.version
     *
     * @param version the value for my_family_member.version
     *
     * @mbg.generated Wed Jan 14 16:48:58 CST 2026
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}