package com.ciaj.boot.modules.my.entity.bo;

import java.math.BigDecimal;
import java.util.Date;

public class MyFamilyBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.user_id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.type
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.day
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.money
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.addr
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.remark
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.create_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.create_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.update_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.update_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.del_flag
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_family_bill.version
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.id
     *
     * @return the value of my_family_bill.id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.id
     *
     * @param id the value for my_family_bill.id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.user_id
     *
     * @return the value of my_family_bill.user_id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.user_id
     *
     * @param userId the value for my_family_bill.user_id
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.type
     *
     * @return the value of my_family_bill.type
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.type
     *
     * @param type the value for my_family_bill.type
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.day
     *
     * @return the value of my_family_bill.day
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.day
     *
     * @param day the value for my_family_bill.day
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.money
     *
     * @return the value of my_family_bill.money
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.money
     *
     * @param money the value for my_family_bill.money
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.addr
     *
     * @return the value of my_family_bill.addr
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.addr
     *
     * @param addr the value for my_family_bill.addr
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.remark
     *
     * @return the value of my_family_bill.remark
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.remark
     *
     * @param remark the value for my_family_bill.remark
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.create_at
     *
     * @return the value of my_family_bill.create_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.create_at
     *
     * @param createAt the value for my_family_bill.create_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.create_time
     *
     * @return the value of my_family_bill.create_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.create_time
     *
     * @param createTime the value for my_family_bill.create_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.update_at
     *
     * @return the value of my_family_bill.update_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.update_at
     *
     * @param updateAt the value for my_family_bill.update_at
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.update_time
     *
     * @return the value of my_family_bill.update_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.update_time
     *
     * @param updateTime the value for my_family_bill.update_time
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.del_flag
     *
     * @return the value of my_family_bill.del_flag
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.del_flag
     *
     * @param delFlag the value for my_family_bill.del_flag
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_family_bill.version
     *
     * @return the value of my_family_bill.version
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_family_bill.version
     *
     * @param version the value for my_family_bill.version
     *
     * @mbg.generated Mon Jul 13 22:34:01 CST 2026
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}