package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import lombok.Data;

import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 09:17:54
 * @Description: www.ciaj.com gen PO
 */
@Data
public class SysAuthPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.user_id
    * 注释：图片URL 
    */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.password
    * 注释：密码 
    */
    private String password;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.salt
    * 注释：密码盐 
    */
    private String salt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.token
    * 注释：token 
    */
    private String token;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.type
    * 注释：验证方式：pwd/token 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_auth.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;
}
