package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import lombok.Data;

import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 09:11:04
 * @Description: www.ciaj.com gen PO
 */
@Data
public class SysConfigPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.config_key
    * 注释：配置KEY 
    */
    private String configKey;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.config_value
    * 注释：配置VALUE 
    */
    private String configValue;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.status
    * 注释：配置状态 
    */
    private String status;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;
}
