package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 09:11:04
 * @Description: www.ciaj.com gen PO
 */
public class SysConfigPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.config_key
    * 注释：配置KEY 
    */
    private String configKey;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.config_value
    * 注释：配置VALUE 
    */
    private String configValue;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.status
    * 注释：配置状态 
    */
    private String status;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_config.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of sys_config.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of sys_config.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：配置KEY 
    * @return the value of sys_config.config_key
    */
    public String getConfigKey() {
         return configKey;
    }

    /**
    * 注释：配置KEY 
    * @param configKey the value of sys_config.config_key
    */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }
    /**
    * 注释：配置VALUE 
    * @return the value of sys_config.config_value
    */
    public String getConfigValue() {
         return configValue;
    }

    /**
    * 注释：配置VALUE 
    * @param configValue the value of sys_config.config_value
    */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
    /**
    * 注释：配置状态 
    * @return the value of sys_config.status
    */
    public String getStatus() {
         return status;
    }

    /**
    * 注释：配置状态 
    * @param status the value of sys_config.status
    */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    /**
    * 注释：备注 
    * @return the value of sys_config.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：备注 
    * @param remark the value of sys_config.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of sys_config.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of sys_config.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of sys_config.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of sys_config.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of sys_config.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of sys_config.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of sys_config.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of sys_config.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of sys_config.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of sys_config.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of sys_config.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of sys_config.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
