package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import lombok.Data;

import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 12:57:43
 * @Description: www.ciaj.com gen PO
 */
@Data
public class SysLogPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.type
    * 注释：日志类型（system,operation,...） 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.username
    * 注释：用户名 
    */
    private String username;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.ip
    * 注释：请求IP 
    */
    private String ip;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.time
    * 注释：请求时长(毫秒) 
    */
    private Long time;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.operation
    * 注释：用户操作 
    */
    private String operation;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.method
    * 注释：请求方法 
    */
    private String method;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.description
    * 注释：备注 
    */
    private String description;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.params
    * 注释：请求参数 
    */
    private String params;
}
