package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 12:57:43
 * @Description: www.ciaj.com gen PO
 */
public class SysLogPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.type
    * 注释：日志类型（system,operation,...） 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.username
    * 注释：用户名 
    */
    private String username;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.ip
    * 注释：请求IP 
    */
    private String ip;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.time
    * 注释：请求时长(毫秒) 
    */
    private Long time;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.operation
    * 注释：用户操作 
    */
    private String operation;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.method
    * 注释：请求方法 
    */
    private String method;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.description
    * 注释：备注 
    */
    private String description;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_log.params
    * 注释：请求参数 
    */
    private String params;


    /**
    * 注释：主键 
    * @return the value of sys_log.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of sys_log.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：日志类型（system,operation,...） 
    * @return the value of sys_log.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：日志类型（system,operation,...） 
    * @param type the value of sys_log.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：用户名 
    * @return the value of sys_log.username
    */
    public String getUsername() {
         return username;
    }

    /**
    * 注释：用户名 
    * @param username the value of sys_log.username
    */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
    /**
    * 注释：请求IP 
    * @return the value of sys_log.ip
    */
    public String getIp() {
         return ip;
    }

    /**
    * 注释：请求IP 
    * @param ip the value of sys_log.ip
    */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
    /**
    * 注释：请求时长(毫秒) 
    * @return the value of sys_log.time
    */
    public Long getTime() {
         return time;
    }

    /**
    * 注释：请求时长(毫秒) 
    * @param time the value of sys_log.time
    */
    public void setTime(Long time) {
        this.time = time;
    }
    /**
    * 注释：用户操作 
    * @return the value of sys_log.operation
    */
    public String getOperation() {
         return operation;
    }

    /**
    * 注释：用户操作 
    * @param operation the value of sys_log.operation
    */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }
    /**
    * 注释：请求方法 
    * @return the value of sys_log.method
    */
    public String getMethod() {
         return method;
    }

    /**
    * 注释：请求方法 
    * @param method the value of sys_log.method
    */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }
    /**
    * 注释：备注 
    * @return the value of sys_log.description
    */
    public String getDescription() {
         return description;
    }

    /**
    * 注释：备注 
    * @param description the value of sys_log.description
    */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of sys_log.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of sys_log.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of sys_log.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of sys_log.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of sys_log.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of sys_log.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of sys_log.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of sys_log.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of sys_log.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of sys_log.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of sys_log.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of sys_log.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
    /**
    * 注释：请求参数 
    * @return the value of sys_log.params
    */
    public String getParams() {
         return params;
    }

    /**
    * 注释：请求参数 
    * @param params the value of sys_log.params
    */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}
