package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.Date;
/**
 * @Author: Ciaj.
 * @Date: 2019-04-12 16:41:56
 * @Description: www.ciaj.com PO
 */
public class SysPermissionPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.name
    * 注释：权限名 
    */
    private String name;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.description
    * 注释：权限描述 
    */
    private String description;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.type
    * 注释：权限类型 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.permission_code
    * 注释：权限码 
    */
    private String permissionCode;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.url
    * 注释：资源路径 
    */
    private String url;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.parent_id
    * 注释：父级id 
    */
    private String parentId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.parent_ids
    * 注释：父级ids 
    */
    private String parentIds;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.available
    * 注释：是否可用（Y/N） 
    */
    private String available;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_permission.del_flag
    * 注释：删除标记 
    */
    private String delFlag;


    /**
    * 注释：主键 
    * @return the value of sys_permission.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of sys_permission.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：权限名 
    * @return the value of sys_permission.name
    */
    public String getName() {
         return name;
    }

    /**
    * 注释：权限名 
    * @param name the value of sys_permission.name
    */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    /**
    * 注释：权限描述 
    * @return the value of sys_permission.description
    */
    public String getDescription() {
         return description;
    }

    /**
    * 注释：权限描述 
    * @param description the value of sys_permission.description
    */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
    /**
    * 注释：权限类型 
    * @return the value of sys_permission.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：权限类型 
    * @param type the value of sys_permission.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：权限码 
    * @return the value of sys_permission.permission_code
    */
    public String getPermissionCode() {
         return permissionCode;
    }

    /**
    * 注释：权限码 
    * @param permissionCode the value of sys_permission.permission_code
    */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }
    /**
    * 注释：资源路径 
    * @return the value of sys_permission.url
    */
    public String getUrl() {
         return url;
    }

    /**
    * 注释：资源路径 
    * @param url the value of sys_permission.url
    */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
    /**
    * 注释：父级id 
    * @return the value of sys_permission.parent_id
    */
    public String getParentId() {
         return parentId;
    }

    /**
    * 注释：父级id 
    * @param parentId the value of sys_permission.parent_id
    */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }
    /**
    * 注释：父级ids 
    * @return the value of sys_permission.parent_ids
    */
    public String getParentIds() {
         return parentIds;
    }

    /**
    * 注释：父级ids 
    * @param parentIds the value of sys_permission.parent_ids
    */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }
    /**
    * 注释：是否可用（Y/N） 
    * @return the value of sys_permission.available
    */
    public String getAvailable() {
         return available;
    }

    /**
    * 注释：是否可用（Y/N） 
    * @param available the value of sys_permission.available
    */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of sys_permission.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of sys_permission.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of sys_permission.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of sys_permission.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of sys_permission.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of sys_permission.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of sys_permission.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of sys_permission.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of sys_permission.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of sys_permission.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}
