package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import lombok.Data;

import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 13:11:15
 * @Description: www.ciaj.com gen PO
 */
@Data
public class SysRolePo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.name
    * 注释：角色名 
    */
    private String name;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.code
    * 注释：角色编码 
    */
    private String code;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.type
    * 注释：角色类型 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.description
    * 注释：角色描述 
    */
    private String description;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.available
    * 注释：角色是否可用（Y/N） 
    */
    private String available;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;
}
