package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import lombok.Data;

import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2019-05-09 13:13:06
 * @Description: www.ciaj.com gen PO
 */
@Data
public class SysRolePermissionRelPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.role_id
    * 注释：角色id 
    */
    private String roleId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.permission_id
    * 注释：权限id 
    */
    private String permissionId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_role_permission_rel.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;
}
