package com.ciaj.boot.modules.sys.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.Date;
/**
 * @Author: Ciaj.
 * @Date: 2019-04-12 17:02:08
 * @Description: www.ciaj.com PO
 */
public class SysUserPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.account
    * 注释：用户账号：手机号、邮箱、其他 
    */
    private String account;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.username
    * 注释：用户名 
    */
    private String username;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.nickname
    * 注释：昵称 
    */
    private String nickname;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.sex
    * 注释：性别， 
    */
    private String sex;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.mobile
    * 注释：电话号码 
    */
    private String mobile;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.email
    * 注释：邮箱 
    */
    private String email;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.birthday
    * 注释：生日 
    */
    private Date birthday;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.province
    * 注释：用户所属省 
    */
    private String province;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.city
    * 注释：用户所属城市 
    */
    private String city;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.district
    * 注释：用户所属区 
    */
    private String district;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.addr
    * 注释：用户详细地址 
    */
    private String addr;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.source
    * 注释：来源，pc/系统  app/移动端 other/其他 ... 
    */
    private String source;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.type
    * 注释：用户类型 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.dept_id
    * 注释：部门ID 
    */
    private String deptId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.locked
    * 注释：锁定状态 Y/N 
    */
    private String locked;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.pic_url
    * 注释：头像地址 
    */
    private String picUrl;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sys_user.del_flag
    * 注释：删除标记 
    */
    private String delFlag;


    /**
    * 注释：主键 
    * @return the value of sys_user.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of sys_user.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：用户账号：手机号、邮箱、其他 
    * @return the value of sys_user.account
    */
    public String getAccount() {
         return account;
    }

    /**
    * 注释：用户账号：手机号、邮箱、其他 
    * @param account the value of sys_user.account
    */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }
    /**
    * 注释：用户名 
    * @return the value of sys_user.username
    */
    public String getUsername() {
         return username;
    }

    /**
    * 注释：用户名 
    * @param username the value of sys_user.username
    */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
    /**
    * 注释：昵称 
    * @return the value of sys_user.nickname
    */
    public String getNickname() {
         return nickname;
    }

    /**
    * 注释：昵称 
    * @param nickname the value of sys_user.nickname
    */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
    /**
    * 注释：性别， 
    * @return the value of sys_user.sex
    */
    public String getSex() {
         return sex;
    }

    /**
    * 注释：性别， 
    * @param sex the value of sys_user.sex
    */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
    /**
    * 注释：电话号码 
    * @return the value of sys_user.mobile
    */
    public String getMobile() {
         return mobile;
    }

    /**
    * 注释：电话号码 
    * @param mobile the value of sys_user.mobile
    */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
    /**
    * 注释：邮箱 
    * @return the value of sys_user.email
    */
    public String getEmail() {
         return email;
    }

    /**
    * 注释：邮箱 
    * @param email the value of sys_user.email
    */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
    /**
    * 注释：生日 
    * @return the value of sys_user.birthday
    */
    public Date getBirthday() {
         return birthday;
    }

    /**
    * 注释：生日 
    * @param birthday the value of sys_user.birthday
    */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    /**
    * 注释：用户所属省 
    * @return the value of sys_user.province
    */
    public String getProvince() {
         return province;
    }

    /**
    * 注释：用户所属省 
    * @param province the value of sys_user.province
    */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
    /**
    * 注释：用户所属城市 
    * @return the value of sys_user.city
    */
    public String getCity() {
         return city;
    }

    /**
    * 注释：用户所属城市 
    * @param city the value of sys_user.city
    */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
    /**
    * 注释：用户所属区 
    * @return the value of sys_user.district
    */
    public String getDistrict() {
         return district;
    }

    /**
    * 注释：用户所属区 
    * @param district the value of sys_user.district
    */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }
    /**
    * 注释：用户详细地址 
    * @return the value of sys_user.addr
    */
    public String getAddr() {
         return addr;
    }

    /**
    * 注释：用户详细地址 
    * @param addr the value of sys_user.addr
    */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
    /**
    * 注释：来源，pc/系统  app/移动端 other/其他 ... 
    * @return the value of sys_user.source
    */
    public String getSource() {
         return source;
    }

    /**
    * 注释：来源，pc/系统  app/移动端 other/其他 ... 
    * @param source the value of sys_user.source
    */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
    /**
    * 注释：用户类型 
    * @return the value of sys_user.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：用户类型 
    * @param type the value of sys_user.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：部门ID 
    * @return the value of sys_user.dept_id
    */
    public String getDeptId() {
         return deptId;
    }

    /**
    * 注释：部门ID 
    * @param deptId the value of sys_user.dept_id
    */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }
    /**
    * 注释：锁定状态 Y/N 
    * @return the value of sys_user.locked
    */
    public String getLocked() {
         return locked;
    }

    /**
    * 注释：锁定状态 Y/N 
    * @param locked the value of sys_user.locked
    */
    public void setLocked(String locked) {
        this.locked = locked == null ? null : locked.trim();
    }
    /**
    * 注释：头像地址 
    * @return the value of sys_user.pic_url
    */
    public String getPicUrl() {
         return picUrl;
    }

    /**
    * 注释：头像地址 
    * @param picUrl the value of sys_user.pic_url
    */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of sys_user.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of sys_user.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of sys_user.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of sys_user.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of sys_user.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of sys_user.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of sys_user.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of sys_user.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of sys_user.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of sys_user.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}
