package com.ciaj.boot.modules.wpe.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2025-07-25 22:28:35
 * @Description: www.ciaj.com gen PO
 */
public class WpeElectricianRecordPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.user_id
    * 注释：用户ID 
    */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.project_id
    * 注释：工程项目ID
    */
    private String projectId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.workday
    * 注释：工作日 
    */
    private Date workday;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.work_start
    * 注释：工作开始时间 
    */
    private Date workStart;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.work_end
    * 注释：工作日结束时间 
    */
    private Date workEnd;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.status
    * 注释：工作状态 
    */
    private String status;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_electrician_record.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of wpe_electrician_record.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of wpe_electrician_record.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：用户ID 
    * @return the value of wpe_electrician_record.user_id
    */
    public String getUserId() {
         return userId;
    }

    /**
    * 注释：用户ID 
    * @param userId the value of wpe_electrician_record.user_id
    */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
    /**
    * 注释：工程项目ID
    * @return the value of wpe_electrician_record.project_id
    */
    public String getProjectId() {
         return projectId;
    }

    /**
    * 注释：工程项目ID
    * @param projectId the value of wpe_electrician_record.project_id
    */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }
    /**
    * 注释：工作日 
    * @return the value of wpe_electrician_record.workday
    */
    public Date getWorkday() {
         return workday;
    }

    /**
    * 注释：工作日 
    * @param workday the value of wpe_electrician_record.workday
    */
    public void setWorkday(Date workday) {
        this.workday = workday;
    }
    /**
    * 注释：工作开始时间 
    * @return the value of wpe_electrician_record.work_start
    */
    public Date getWorkStart() {
         return workStart;
    }

    /**
    * 注释：工作开始时间 
    * @param workStart the value of wpe_electrician_record.work_start
    */
    public void setWorkStart(Date workStart) {
        this.workStart = workStart;
    }
    /**
    * 注释：工作日结束时间 
    * @return the value of wpe_electrician_record.work_end
    */
    public Date getWorkEnd() {
         return workEnd;
    }

    /**
    * 注释：工作日结束时间 
    * @param workEnd the value of wpe_electrician_record.work_end
    */
    public void setWorkEnd(Date workEnd) {
        this.workEnd = workEnd;
    }
    /**
    * 注释：备注 
    * @return the value of wpe_electrician_record.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：备注 
    * @param remark the value of wpe_electrician_record.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：工作状态 
    * @return the value of wpe_electrician_record.status
    */
    public String getStatus() {
         return status;
    }

    /**
    * 注释：工作状态 
    * @param status the value of wpe_electrician_record.status
    */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of wpe_electrician_record.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of wpe_electrician_record.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of wpe_electrician_record.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of wpe_electrician_record.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of wpe_electrician_record.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of wpe_electrician_record.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of wpe_electrician_record.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of wpe_electrician_record.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of wpe_electrician_record.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of wpe_electrician_record.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of wpe_electrician_record.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of wpe_electrician_record.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
