package com.ciaj.boot.modules.wpe.entity.po;

import com.ciaj.base.BaseEntity;

import java.math.BigDecimal;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2025-09-01 16:06:42
 * @Description: www.ciaj.com gen PO
 */
public class WpeFinalStatementPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.user_id
    * 注释：用户ID 
    */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.day
    * 注释：结算日 
    */
    private Date day;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.money
    * 注释：款项金额
    */
    private BigDecimal money;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_final_statement.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of wpe_final_statement.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of wpe_final_statement.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：用户ID 
    * @return the value of wpe_final_statement.user_id
    */
    public String getUserId() {
         return userId;
    }

    /**
    * 注释：用户ID 
    * @param userId the value of wpe_final_statement.user_id
    */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
    /**
    * 注释：结算日 
    * @return the value of wpe_final_statement.day
    */
    public Date getDay() {
         return day;
    }

    /**
    * 注释：结算日 
    * @param day the value of wpe_final_statement.day
    */
    public void setDay(Date day) {
        this.day = day;
    }
    /**
    * 注释：款项金额
    * @return the value of wpe_final_statement.money
    */
    public BigDecimal getMoney() {
         return money;
    }

    /**
    * 注释：款项金额
    * @param money the value of wpe_final_statement.money
    */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    /**
    * 注释：备注 
    * @return the value of wpe_final_statement.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：备注 
    * @param remark the value of wpe_final_statement.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of wpe_final_statement.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of wpe_final_statement.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of wpe_final_statement.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of wpe_final_statement.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of wpe_final_statement.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of wpe_final_statement.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of wpe_final_statement.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of wpe_final_statement.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of wpe_final_statement.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of wpe_final_statement.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of wpe_final_statement.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of wpe_final_statement.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
