package com.ciaj.boot.modules.wpe.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2025-07-27 09:31:59
 * @Description: www.ciaj.com gen PO
 */
public class WpeProjectPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.project_name
    * 注释：工程项目名称 
    */
    private String projectName;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.addr
    * 注释：地址 
    */
    private String addr;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.house_type
    * 注释：项目户型 
    */
    private String houseType;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.decoration_type
    * 注释：装修类型 
    */
    private String decorationType;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column wpe_project.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of wpe_project.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of wpe_project.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：工程项目名称 
    * @return the value of wpe_project.project_name
    */
    public String getProjectName() {
         return projectName;
    }

    /**
    * 注释：工程项目名称 
    * @param projectName the value of wpe_project.project_name
    */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }
    /**
    * 注释：地址 
    * @return the value of wpe_project.addr
    */
    public String getAddr() {
         return addr;
    }

    /**
    * 注释：地址 
    * @param addr the value of wpe_project.addr
    */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
    /**
    * 注释：备注 
    * @return the value of wpe_project.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：备注 
    * @param remark the value of wpe_project.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：项目户型 
    * @return the value of wpe_project.house_type
    */
    public String getHouseType() {
         return houseType;
    }

    /**
    * 注释：项目户型 
    * @param houseType the value of wpe_project.house_type
    */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }
    /**
    * 注释：装修类型 
    * @return the value of wpe_project.decoration_type
    */
    public String getDecorationType() {
         return decorationType;
    }

    /**
    * 注释：装修类型 
    * @param decorationType the value of wpe_project.decoration_type
    */
    public void setDecorationType(String decorationType) {
        this.decorationType = decorationType == null ? null : decorationType.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of wpe_project.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of wpe_project.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of wpe_project.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of wpe_project.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of wpe_project.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of wpe_project.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of wpe_project.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of wpe_project.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of wpe_project.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of wpe_project.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of wpe_project.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of wpe_project.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
