package com.ciaj.boot.modules.my.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2026-01-14 16:21:01
 * @Description: www.ciaj.com gen PO
 */
public class MyFamilyPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.name
    * 注释：家庭名称 
    */
    private String name;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.code
    * 注释：家庭编码 
    */
    private String code;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.enabled
    * 注释：是否可用Y/N 
    */
    private String enabled;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.area_id
    * 注释：家庭区域 
    */
    private String areaId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.addr
    * 注释：家庭详细地址 
    */
    private String addr;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.description
    * 注释：家庭描述 
    */
    private String description;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of my_family.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of my_family.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：家庭名称 
    * @return the value of my_family.name
    */
    public String getName() {
         return name;
    }

    /**
    * 注释：家庭名称 
    * @param name the value of my_family.name
    */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    /**
    * 注释：家庭编码 
    * @return the value of my_family.code
    */
    public String getCode() {
         return code;
    }

    /**
    * 注释：家庭编码 
    * @param code the value of my_family.code
    */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
    /**
    * 注释：是否可用Y/N 
    * @return the value of my_family.enabled
    */
    public String getEnabled() {
         return enabled;
    }

    /**
    * 注释：是否可用Y/N 
    * @param enabled the value of my_family.enabled
    */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }
    /**
    * 注释：家庭区域 
    * @return the value of my_family.area_id
    */
    public String getAreaId() {
         return areaId;
    }

    /**
    * 注释：家庭区域 
    * @param areaId the value of my_family.area_id
    */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }
    /**
    * 注释：家庭详细地址 
    * @return the value of my_family.addr
    */
    public String getAddr() {
         return addr;
    }

    /**
    * 注释：家庭详细地址 
    * @param addr the value of my_family.addr
    */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
    /**
    * 注释：家庭描述 
    * @return the value of my_family.description
    */
    public String getDescription() {
         return description;
    }

    /**
    * 注释：家庭描述 
    * @param description the value of my_family.description
    */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of my_family.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of my_family.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of my_family.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of my_family.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of my_family.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of my_family.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of my_family.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of my_family.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of my_family.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of my_family.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of my_family.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of my_family.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
