package com.ciaj.boot.modules.my.entity.po;

import com.ciaj.base.BaseEntity;

import java.math.BigDecimal;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2026-07-13 22:34:02
 * @Description: www.ciaj.com gen PO
 */
public class MyFamilyBillPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.user_id
    * 注释：用户ID 
    */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.type
    * 注释：类型 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.day
    * 注释：日期 
    */
    private Date day;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.money
    * 注释：款项 
    */
    private BigDecimal money;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.addr
    * 注释：地址 
    */
    private String addr;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.remark
    * 注释：备注 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_bill.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of my_family_bill.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of my_family_bill.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：用户ID 
    * @return the value of my_family_bill.user_id
    */
    public String getUserId() {
         return userId;
    }

    /**
    * 注释：用户ID 
    * @param userId the value of my_family_bill.user_id
    */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
    /**
    * 注释：类型 
    * @return the value of my_family_bill.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：类型 
    * @param type the value of my_family_bill.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：日期 
    * @return the value of my_family_bill.day
    */
    public Date getDay() {
         return day;
    }

    /**
    * 注释：日期 
    * @param day the value of my_family_bill.day
    */
    public void setDay(Date day) {
        this.day = day;
    }
    /**
    * 注释：款项 
    * @return the value of my_family_bill.money
    */
    public BigDecimal getMoney() {
         return money;
    }

    /**
    * 注释：款项 
    * @param money the value of my_family_bill.money
    */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    /**
    * 注释：地址 
    * @return the value of my_family_bill.addr
    */
    public String getAddr() {
         return addr;
    }

    /**
    * 注释：地址 
    * @param addr the value of my_family_bill.addr
    */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
    /**
    * 注释：备注 
    * @return the value of my_family_bill.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：备注 
    * @param remark the value of my_family_bill.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of my_family_bill.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of my_family_bill.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of my_family_bill.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of my_family_bill.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of my_family_bill.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of my_family_bill.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of my_family_bill.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of my_family_bill.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of my_family_bill.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of my_family_bill.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of my_family_bill.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of my_family_bill.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
