package com.ciaj.boot.modules.my.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2026-01-14 16:48:58
 * @Description: www.ciaj.com gen PO
 */
public class MyFamilyMemberPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.family_id
    * 注释：家庭ID 
    */
    private String familyId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.user_id
    * 注释：用户ID 
    */
    private String userId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.type
    * 注释：成员类型 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column my_family_member.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of my_family_member.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of my_family_member.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：家庭ID 
    * @return the value of my_family_member.family_id
    */
    public String getFamilyId() {
         return familyId;
    }

    /**
    * 注释：家庭ID 
    * @param familyId the value of my_family_member.family_id
    */
    public void setFamilyId(String familyId) {
        this.familyId = familyId == null ? null : familyId.trim();
    }
    /**
    * 注释：用户ID 
    * @return the value of my_family_member.user_id
    */
    public String getUserId() {
         return userId;
    }

    /**
    * 注释：用户ID 
    * @param userId the value of my_family_member.user_id
    */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
    /**
    * 注释：成员类型 
    * @return the value of my_family_member.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：成员类型 
    * @param type the value of my_family_member.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of my_family_member.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of my_family_member.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of my_family_member.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of my_family_member.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of my_family_member.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of my_family_member.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of my_family_member.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of my_family_member.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of my_family_member.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of my_family_member.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of my_family_member.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of my_family_member.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
