package ${targetPackage};

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
<#assign dateTime = .now>
/**
 * @Author: ${author}
 * @Date: ${dateTime?string["yyyy-MM-dd HH:mm:ss"]}
 * @Description: ${description} PO
 */
public class ${tableClass.shortClassName}Po extends BaseEntity {
<#if tableClass.allFields??>
    <#list tableClass.allFields as field>
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column ${tableClass.tableName}.${field.columnName}
    * <#if field.remarks??>注释：${field.remarks} </#if>
    */
    private ${field.shortTypeName} ${field.fieldName};

    </#list>
</#if>

<#if tableClass.allFields??>
<#list tableClass.allFields as field>
    /**
    * <#if field.remarks??>注释：${field.remarks} </#if>
    * @return the value of ${tableClass.tableName}.${field.columnName}
    */
    public ${field.shortTypeName} get${field.fieldName?cap_first}() {
         return ${field.fieldName};
    }

    /**
    * <#if field.remarks??>注释：${field.remarks} </#if>
    * @param ${field.fieldName} the value of ${tableClass.tableName}.${field.columnName}
    */
    public void set${field.fieldName?cap_first}(${field.shortTypeName} ${field.fieldName}) {
        <#if field.stringColumn==true>this.${field.fieldName} = ${field.fieldName} == null ? null : ${field.fieldName}.trim();<#else>this.${field.fieldName} = ${field.fieldName};</#if>
    }
</#list>
</#if>
}
