package com.ciaj.boot.modules.task.entity.po;

import com.ciaj.base.BaseEntity;
import java.util.*;
import java.lang.*;
/**
 * @Author: Ciaj.
 * @Date: 2026-06-02 21:57:07
 * @Description: www.ciaj.com gen PO
 */
public class TaskSchedulerPo extends BaseEntity {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.id
    * 注释：主键 
    */
    private String id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.type
    * 注释：类型fixedRate、fixedDelay、cron 
    */
    private String type;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.name
    * 注释：名称 
    */
    private String name;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.remark
    * 注释：描述 
    */
    private String remark;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.bean_name
    * 注释：bean名称 
    */
    private String beanName;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.cron
    * 注释：cron表达式 
    */
    private String cron;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.delay
    * 注释：间隔毫秒 
    */
    private Long delay;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.status
    * 注释：0 ok 1 禁用 
    */
    private String status;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.create_at
    * 注释：创建人 
    */
    private String createAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.create_time
    * 注释：创建时间 
    */
    private Date createTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.update_at
    * 注释：更新人 
    */
    private String updateAt;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.update_time
    * 注释：更新时间 
    */
    private Date updateTime;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.del_flag
    * 注释：删除标记 
    */
    private String delFlag;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column task_scheduler.version
    * 注释：版本号0为不可修改，1+可修改 
    */
    private Integer version;


    /**
    * 注释：主键 
    * @return the value of task_scheduler.id
    */
    public String getId() {
         return id;
    }

    /**
    * 注释：主键 
    * @param id the value of task_scheduler.id
    */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
    /**
    * 注释：类型fixedRate、fixedDelay、cron 
    * @return the value of task_scheduler.type
    */
    public String getType() {
         return type;
    }

    /**
    * 注释：类型fixedRate、fixedDelay、cron 
    * @param type the value of task_scheduler.type
    */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    /**
    * 注释：名称 
    * @return the value of task_scheduler.name
    */
    public String getName() {
         return name;
    }

    /**
    * 注释：名称 
    * @param name the value of task_scheduler.name
    */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    /**
    * 注释：描述 
    * @return the value of task_scheduler.remark
    */
    public String getRemark() {
         return remark;
    }

    /**
    * 注释：描述 
    * @param remark the value of task_scheduler.remark
    */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    /**
    * 注释：bean名称 
    * @return the value of task_scheduler.bean_name
    */
    public String getBeanName() {
         return beanName;
    }

    /**
    * 注释：bean名称 
    * @param beanName the value of task_scheduler.bean_name
    */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }
    /**
    * 注释：cron表达式 
    * @return the value of task_scheduler.cron
    */
    public String getCron() {
         return cron;
    }

    /**
    * 注释：cron表达式 
    * @param cron the value of task_scheduler.cron
    */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }
    /**
    * 注释：间隔毫秒 
    * @return the value of task_scheduler.delay
    */
    public Long getDelay() {
         return delay;
    }

    /**
    * 注释：间隔毫秒 
    * @param delay the value of task_scheduler.delay
    */
    public void setDelay(Long delay) {
        this.delay = delay;
    }
    /**
    * 注释：0 ok 1 禁用 
    * @return the value of task_scheduler.status
    */
    public String getStatus() {
         return status;
    }

    /**
    * 注释：0 ok 1 禁用 
    * @param status the value of task_scheduler.status
    */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    /**
    * 注释：创建人 
    * @return the value of task_scheduler.create_at
    */
    public String getCreateAt() {
         return createAt;
    }

    /**
    * 注释：创建人 
    * @param createAt the value of task_scheduler.create_at
    */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }
    /**
    * 注释：创建时间 
    * @return the value of task_scheduler.create_time
    */
    public Date getCreateTime() {
         return createTime;
    }

    /**
    * 注释：创建时间 
    * @param createTime the value of task_scheduler.create_time
    */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
    * 注释：更新人 
    * @return the value of task_scheduler.update_at
    */
    public String getUpdateAt() {
         return updateAt;
    }

    /**
    * 注释：更新人 
    * @param updateAt the value of task_scheduler.update_at
    */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }
    /**
    * 注释：更新时间 
    * @return the value of task_scheduler.update_time
    */
    public Date getUpdateTime() {
         return updateTime;
    }

    /**
    * 注释：更新时间 
    * @param updateTime the value of task_scheduler.update_time
    */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /**
    * 注释：删除标记 
    * @return the value of task_scheduler.del_flag
    */
    public String getDelFlag() {
         return delFlag;
    }

    /**
    * 注释：删除标记 
    * @param delFlag the value of task_scheduler.del_flag
    */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @return the value of task_scheduler.version
    */
    public Integer getVersion() {
         return version;
    }

    /**
    * 注释：版本号0为不可修改，1+可修改 
    * @param version the value of task_scheduler.version
    */
    public void setVersion(Integer version) {
        this.version = version;
    }
}
