package com.ciaj.boot.modules.wpe.entity.bo;

import java.math.BigDecimal;
import java.util.Date;

public class WpeElectricianRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.user_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.project_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.workday
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Date workday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.work_start
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Date workStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.work_end
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Date workEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.remark
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.status
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.labour_cost
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private BigDecimal labourCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.create_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.create_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.update_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.update_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.del_flag
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_electrician_record.version
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.id
     *
     * @return the value of wpe_electrician_record.id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.id
     *
     * @param id the value for wpe_electrician_record.id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.user_id
     *
     * @return the value of wpe_electrician_record.user_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.user_id
     *
     * @param userId the value for wpe_electrician_record.user_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.project_id
     *
     * @return the value of wpe_electrician_record.project_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.project_id
     *
     * @param projectId the value for wpe_electrician_record.project_id
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.workday
     *
     * @return the value of wpe_electrician_record.workday
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Date getWorkday() {
        return workday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.workday
     *
     * @param workday the value for wpe_electrician_record.workday
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setWorkday(Date workday) {
        this.workday = workday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.work_start
     *
     * @return the value of wpe_electrician_record.work_start
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Date getWorkStart() {
        return workStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.work_start
     *
     * @param workStart the value for wpe_electrician_record.work_start
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setWorkStart(Date workStart) {
        this.workStart = workStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.work_end
     *
     * @return the value of wpe_electrician_record.work_end
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Date getWorkEnd() {
        return workEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.work_end
     *
     * @param workEnd the value for wpe_electrician_record.work_end
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setWorkEnd(Date workEnd) {
        this.workEnd = workEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.remark
     *
     * @return the value of wpe_electrician_record.remark
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.remark
     *
     * @param remark the value for wpe_electrician_record.remark
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.status
     *
     * @return the value of wpe_electrician_record.status
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.status
     *
     * @param status the value for wpe_electrician_record.status
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.labour_cost
     *
     * @return the value of wpe_electrician_record.labour_cost
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public BigDecimal getLabourCost() {
        return labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.labour_cost
     *
     * @param labourCost the value for wpe_electrician_record.labour_cost
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setLabourCost(BigDecimal labourCost) {
        this.labourCost = labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.create_at
     *
     * @return the value of wpe_electrician_record.create_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.create_at
     *
     * @param createAt the value for wpe_electrician_record.create_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.create_time
     *
     * @return the value of wpe_electrician_record.create_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.create_time
     *
     * @param createTime the value for wpe_electrician_record.create_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.update_at
     *
     * @return the value of wpe_electrician_record.update_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.update_at
     *
     * @param updateAt the value for wpe_electrician_record.update_at
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.update_time
     *
     * @return the value of wpe_electrician_record.update_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.update_time
     *
     * @param updateTime the value for wpe_electrician_record.update_time
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.del_flag
     *
     * @return the value of wpe_electrician_record.del_flag
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.del_flag
     *
     * @param delFlag the value for wpe_electrician_record.del_flag
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_electrician_record.version
     *
     * @return the value of wpe_electrician_record.version
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_electrician_record.version
     *
     * @param version the value for wpe_electrician_record.version
     *
     * @mbg.generated Fri Jul 25 22:28:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}