package com.ciaj.boot.modules.wpe.entity.bo;

import java.math.BigDecimal;
import java.util.Date;

public class WpeFinalStatement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.user_id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.day
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private Date day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.money
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.remark
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.create_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.create_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.update_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.update_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.del_flag
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_final_statement.version
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.id
     *
     * @return the value of wpe_final_statement.id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.id
     *
     * @param id the value for wpe_final_statement.id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.user_id
     *
     * @return the value of wpe_final_statement.user_id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.user_id
     *
     * @param userId the value for wpe_final_statement.user_id
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.day
     *
     * @return the value of wpe_final_statement.day
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.day
     *
     * @param day the value for wpe_final_statement.day
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.money
     *
     * @return the value of wpe_final_statement.money
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.money
     *
     * @param money the value for wpe_final_statement.money
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.remark
     *
     * @return the value of wpe_final_statement.remark
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.remark
     *
     * @param remark the value for wpe_final_statement.remark
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.create_at
     *
     * @return the value of wpe_final_statement.create_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.create_at
     *
     * @param createAt the value for wpe_final_statement.create_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.create_time
     *
     * @return the value of wpe_final_statement.create_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.create_time
     *
     * @param createTime the value for wpe_final_statement.create_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.update_at
     *
     * @return the value of wpe_final_statement.update_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.update_at
     *
     * @param updateAt the value for wpe_final_statement.update_at
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.update_time
     *
     * @return the value of wpe_final_statement.update_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.update_time
     *
     * @param updateTime the value for wpe_final_statement.update_time
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.del_flag
     *
     * @return the value of wpe_final_statement.del_flag
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.del_flag
     *
     * @param delFlag the value for wpe_final_statement.del_flag
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_final_statement.version
     *
     * @return the value of wpe_final_statement.version
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_final_statement.version
     *
     * @param version the value for wpe_final_statement.version
     *
     * @mbg.generated Mon Sep 01 16:06:42 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}