package com.ciaj.boot.modules.wpe.entity.bo;

import java.util.Date;

public class WpeProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.id
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.project_name
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.addr
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.remark
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.house_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String houseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.decoration_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String decorationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.create_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.create_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.update_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.update_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.del_flag
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpe_project.version
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.id
     *
     * @return the value of wpe_project.id
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.id
     *
     * @param id the value for wpe_project.id
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.project_name
     *
     * @return the value of wpe_project.project_name
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.project_name
     *
     * @param projectName the value for wpe_project.project_name
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.addr
     *
     * @return the value of wpe_project.addr
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.addr
     *
     * @param addr the value for wpe_project.addr
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.remark
     *
     * @return the value of wpe_project.remark
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.remark
     *
     * @param remark the value for wpe_project.remark
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.house_type
     *
     * @return the value of wpe_project.house_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.house_type
     *
     * @param houseType the value for wpe_project.house_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.decoration_type
     *
     * @return the value of wpe_project.decoration_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getDecorationType() {
        return decorationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.decoration_type
     *
     * @param decorationType the value for wpe_project.decoration_type
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setDecorationType(String decorationType) {
        this.decorationType = decorationType == null ? null : decorationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.create_at
     *
     * @return the value of wpe_project.create_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.create_at
     *
     * @param createAt the value for wpe_project.create_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setCreateAt(String createAt) {
        this.createAt = createAt == null ? null : createAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.create_time
     *
     * @return the value of wpe_project.create_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.create_time
     *
     * @param createTime the value for wpe_project.create_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.update_at
     *
     * @return the value of wpe_project.update_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.update_at
     *
     * @param updateAt the value for wpe_project.update_at
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt == null ? null : updateAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.update_time
     *
     * @return the value of wpe_project.update_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.update_time
     *
     * @param updateTime the value for wpe_project.update_time
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.del_flag
     *
     * @return the value of wpe_project.del_flag
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.del_flag
     *
     * @param delFlag the value for wpe_project.del_flag
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpe_project.version
     *
     * @return the value of wpe_project.version
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpe_project.version
     *
     * @param version the value for wpe_project.version
     *
     * @mbg.generated Sun Jul 27 09:31:59 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}